package com.zdmoney.mapper;


import com.zdmoney.models.CustomerRelationship;
import com.zdmoney.webservice.api.dto.ym.CustomerRelationShipDto;

import java.math.BigDecimal;

public interface CustomerRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    int insert(CustomerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    int insertSelective(CustomerRelationShipDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    CustomerRelationship selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.CUSTOMER_RELATIONSHIP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerRelationShipDto record);

    CustomerRelationShipDto selectCountByCmNumber(String cmNumber);

    int selectTotalCount();
}