package com.zdmoney.mapper.order;


import com.zdmoney.models.order.ViewOrder;
import com.zdmoney.webservice.api.dto.ym.ViewOrderDto;
import com.zdmoney.webservice.api.dto.ym.vo.ViewOrderVo;

import java.util.List;

public interface ViewOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.VIEW_ORDER
     *
     * @mbggenerated
     */
    int insert(ViewOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAOCAIBAO.VIEW_ORDER
     *
     * @mbggenerated
     */
    int insertSelective(ViewOrder record);

    /**
     * 查询订单信息
     * @param viewOrderDto
     * @return
     */
    List<ViewOrderVo> getOrderInfo(ViewOrderDto viewOrderDto);
}