package com.zdmoney.models;

import java.math.BigDecimal;
import java.util.Date;

public class CustomerRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_NUMBER
     *
     * @mbggenerated
     */
    private String custNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_TYPE
     *
     * @mbggenerated
     */
    private BigDecimal custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.INVITE_CODE
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    private int count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.ID
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.ID
     *
     * @param id the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_NUMBER
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_NUMBER
     *
     * @mbggenerated
     */
    public String getCustNumber() {
        return custNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_NUMBER
     *
     * @param custNumber the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_NUMBER
     *
     * @mbggenerated
     */
    public void setCustNumber(String custNumber) {
        this.custNumber = custNumber == null ? null : custNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_TYPE
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_TYPE
     *
     * @param custType the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.CUST_TYPE
     *
     * @mbggenerated
     */
    public void setCustType(BigDecimal custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.INVITE_CODE
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.INVITE_CODE
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.INVITE_CODE
     *
     * @param inviteCode the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.INVITE_CODE
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CREATE_DATE
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.CREATE_DATE
     *
     * @param createDate the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.MODIFY_DATE
     *
     * @return the value of LAOCAIBAO.CUSTOMER_RELATIONSHIP.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAOCAIBAO.CUSTOMER_RELATIONSHIP.MODIFY_DATE
     *
     * @param modifyDate the value for LAOCAIBAO.CUSTOMER_RELATIONSHIP.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Override
    public String toString() {
        return "CustomerRelationship{" +
                "id=" + id +
                ", custNumber='" + custNumber + '\'' +
                ", custType=" + custType +
                ", inviteCode='" + inviteCode + '\'' +
                ", createDate=" + createDate +
                ", modifyDate=" + modifyDate +
                ", count=" + count +
                '}';
    }
}